name: licensor
version: 0.4.0

synopsis: A license compatibility helper
description: A license compatibility helper.

category: Distribution

stability: Experimental
github: jpvillaisaza/licensor
homepage: https://jpvillaisaza.co/licensor

author: Juan Pedro Villa Isaza <jpvillaisaza@gmail.com>
maintainer: Juan Pedro Villa Isaza <jpvillaisaza@gmail.com>
copyright: 2016 Juan Pedro Villa Isaza

license-file: LICENSE.md

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - Cabal
  - base
  - containers
  - directory

ghc-options:
  - -Wall

library:
  source-dirs:
    src
  dependencies:
    - process

executable:
  source-dirs:
    app
  main:
    Main.hs
  dependencies:
    - cmdargs
    - licensor
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
